stages:
  - Timestamp
  - Platform Specific
  - OpenGE
  - Build Pass 1
  - Build Libraries
  - Build Pass 2
  - Publish
  - End

include:
  - Build/.platform-maclogging.gitlab-ci.yml
  - Build/.platform-autodiscovery.gitlab-ci.yml
  - Build/.openge-shim.gitlab-ci.yml
  - Build/.openge-agent.gitlab-ci.yml
  - Build/.uefs-client.gitlab-ci.yml
  - Build/.uefs-daemon.gitlab-ci.yml
  - Build/.uet-lib.gitlab-ci.yml
  - Build/.uet-pass-1.gitlab-ci.yml
  - Build/.uet-pass-2.gitlab-ci.yml
  - Build/.uet-shim.gitlab-ci.yml
  - Build/.uet-openge-test.gitlab-ci.yml
  - Build/.publish-nuget.gitlab-ci.yml
  - Build/.publish-github.gitlab-ci.yml
  - Build/.publish-container-uefs.gitlab-ci.yml

variables:
  DEVELOPER_DIR: /Users/Shared/UET/SDKs/Mac-14.1/Xcode.app
  FRAMEWORK_TARGET: net7.0
  UET_BUILDING_ON_BUILD_SERVER: "true"
  MSBUILDDISABLENODEREUSE: "1"
  
"Timestamp":
  stage: Timestamp
  tags:
    - redpoint-games-windows
  interruptible: true
  script: |
    $Timestamp = ([DateTime]::UtcNow)
    $PackageVersion = "$($Timestamp.Year).$($Timestamp.DayOfYear + 1000).$(($Timestamp.Hour * 60) + $Timestamp.Minute)"
    Set-Content -NoNewline -Path "package.version" -Value "$PackageVersion"
  artifacts:
    paths:
      - package.version